-- liquibase formatted sql

-- changeset anton:1

create table student
(
    id         integer generated by default as identity
        constraint student_pkey
            primary key,
    first_name varchar(255),
    last_name  varchar(255),
    password   varchar(255),
    role       varchar(255)
);

create table log
(
    id         integer generated by default as identity
        constraint log_pkey
            primary key,
    date       date,
    message    varchar(255),
    student_id integer
        constraint log_student
            references student
);

-- changeset anton:2

INSERT INTO student(first_name, last_name)
VALUES ('Ольга', 'Макеева'),
       ('Ольга', 'Соловьева'),
       ('Полина', 'Стефанская'),
       ('Евгений', 'Ильин'),
       ('Алексей', 'Кузнецов'),
       ('Даниль', 'Адигамов'),
       ('Юлия', 'Суслова'),
       ('Максим', 'Ростиславский'),
       ('Эдуард', 'Гайниев'),
       ('Юрий', 'Иванов'),
       ('Иван', 'Моря'),
       ('Роман', 'Головачев'),
       ('Игорь', 'Зубров'),
       ('Антон', 'Кадачигов'),
       ('Андрей', 'Булавин'),
       ('Максим', 'Маковеев'),
       ('Евгений', 'Юруть'),
       ('Арсений', 'Виноградов'),
       ('Александр', 'Варкан'),
       ('Олег', 'Гвоздь');




